version: '2'
services:
  db:
    image: mysql:5.7 
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"

  web:
    build: .
    command: bundle exec puma -C /GCBGB/config/puma.rb
    volumes:
      - .:/GCBGB
    ports:
      - "3000:3000"
    links:
      - db
    # environment:
    #   RAILS_ENV: 'production'
    environment:
      - "SELENIUM_DRIVER_URL=http://selenium_chrome:4444/wd/hub"
    tty: true

  nginx:
    build: containers/nginx
    ports:
      - "80:80"
    volumes_from:
      - web
    depends_on:
      - web
    
  selenium_chrome:
    image: selenium/standalone-chrome-debug
    logging:
      driver: none
  
  mail:
    image: yaasita/docker_blackhole_mail_server
    ports:
      - "1080:80"
